sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2

  # https://docs.travis-ci.com/user/database-setup/#PostgreSQL
before_script:
- psql -c 'create database voting_system' -U postgres
- psql -c 'create user "user"; grant all privileges on database voting_system to "user"' -U postgres
#https://stackoverflow.com/questions/41285388/travis-does-not-compile-the-project
env:
- MAVEN_VERSION=3.5.4
install:
- "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
- "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
script: "./mvnw --show-version --errors --batch-mode -Prun-its clean verify"